version: 2

models:
    -   name: dim_employees
        description: "Nossa tabela de funcion치rios"
        columns:
            -   name: businessentityid
                description: "A chave prim치ria original da tabela"
                tests:
                    - unique
                    - not_null
    -   name: dim_products
        description: "Nossa tabela de produtos"
        columns:
            -   name: productid
                description: "A chave prim치ria original da tabela"
                tests:
                    - unique
                    - not_null
    -   name: fact_sales
        description: "Nossa tabela de produtos"
        columns:
            -   name: salesorderid
                description: "A chave prim치ria original da tabela"
                tests:
                    - unique
                    - not_null        