version: 2

models:
    -   name: dim_employees
        description: "Nossa tabela de funcionários"
        columns:
            -   name: businessentityid
                description: "A chave primária original da tabela"
                tests:
                    - unique
                    - not_null
    -   name: dim_products
        description: "Nossa tabela de produtos"
        columns:
            -   name: productid
                description: "A chave primária original da tabela"
                tests:
                    - unique
                    - not_null
    -   name: fact_sales
        description: "Nossa tabela de produtos"
        columns:
            -   name: id_do_pedido
                description: "A chave primária original da tabela"
                tests:
                    - not_null        
    -   name: dim_transportadora
        description: "Nossos transportadores"
        columns:
            -   name: shipmethodid
                description: "A chave primária original da tabela"
                tests:
                    - unique
                    - not_null   
    -   name: dim_fornecedor
        description: "Nossos fornecedores"
        columns:
            -   name: fornecedor_sk
                description: "A chave primária original da tabela"
                tests:
                    - unique
                    - not_null   